# Generated by Django 5.2.7 on 2025-11-29 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBlock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priorites', 'datetocm'], 'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Творець'),
        ),
        migrations.AlterField(
            model_name='task',
            name='datetocm',
            field=models.DateTimeField(verbose_name='Дата виконання'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priorites',
            field=models.CharField(choices=[('ndi', 'Не відкладно важливе'), ('tmi', 'Найважливіше'), ('mi', 'Важливіше'), ('i', 'Важливе'), ('ni', 'Не важливе')], default='i', max_length=5, verbose_name='Пріоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('make', 'Зробити'), ('inprogress', 'В процесі'), ('complete', 'Виконано'), ('declined', 'Відкладено')], default='make', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
