# Generated by Django 5.2.7 on 2025-12-12 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBlock', '0002_alter_task_options_alter_task_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetocm',
            field=models.DateTimeField(verbose_name='Дата закінчення'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('upltime', models.TimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to=settings.AUTH_USER_MODEL, verbose_name='Творець')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to='TaskBlock.task', verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ['upltime'],
            },
        ),
    ]
